version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - if [ -d lib ]; then cd lib && zip -r9 ../deployment_package.zip . && cd ..; else echo "No dependencies to zip."; fi
      - zip -g deployment_package.zip getStudents.py  # Add main Lambda code
  post_build:
  commands:
    - echo "Uploading deployment package to S3..."
    - aws s3 cp deployment_package.zip s3://my23princebucket/deployment_package.zip
    - if [ $? -eq 0 ]; then echo "Upload to S3 successful."; else echo "Upload to S3 failed." && exit 1; fi
    - echo "Updating Lambda function code from S3..."
    - aws lambda update-function-code --function-name Fully-Automated-Serverless-API- --s3-bucket my23princebucket --s3-key deployment_package.zip
    - if [ $? -eq 0 ]; then echo "Lambda function update successful."; else echo "Lambda function update failed." && exit 1; fi
    - echo "Deployment completed successfully!"

